Note dialog title enhancement
c1rcle/yellow-notes-frontend pull request #114
Opened 2020-04-28 17:48 UTC by wkud

Fixes #94

2020-04-28 18:13 UTC, c1rcle commented on src/components/pages/Notes/NoteDialog/NoteDialogForm.js
> +  const [focus, setFocus] = useState(false);
These two states could be in a single object.

2020-04-28 18:24 UTC, c1rcle commented on src/components/pages/Notes/NoteDialog/NoteDialogForm.js
> +            style={{
The title should be bold.

2020-04-29 12:21 UTC, wkud commented on src/components/pages/Notes/NoteDialog/NoteDialogForm.js
> +            style={{
done

2020-04-29 12:21 UTC, wkud commented on src/components/pages/Notes/NoteDialog/NoteDialogForm.js
> +            style={{
done

2020-04-29 13:58 UTC, c1rcle requested changes

2020-04-29 13:58 UTC, c1rcle commented on src/components/pages/Notes/NoteDialog/NoteDialogForm.js
> +              fontWeight: 'bold'
Static styles should be defined as a class in a separate `css` file.

2020-04-29 15:44 UTC, c1rcle approved these changes

2020-04-29 18:54 UTC, merged